### ISSUE TITLE
Fix Reference GTF 

### ISSUE THREAD

**Issue by vkkodali** [NCBI-Codeathons/airbending_isoseq#4]
RefSeq GTF is here: https://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/9606/109.20200228/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.gtf.gz

This does not have the 'transcript' lines. We need to add these lines. TALON has a helper script that will do this. Run that script and save the output for use with the pipeline.

**Comment by e-hutchins** [comment]
Putting the workflow here while we're waiting for access to the instance. I tested this out locally and it works, or at least the TALON script runs.

0a) download kentutils
`rsync -aP rsync://hgdownload.soe.ucsc.edu/genome/admin/exe/linux.x86_64/ ./`

0b) download TALON
`git clone https://github.com/dewyman/TALON.git`

1) get gff file, which has transcript lines
`wget https://ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/9606/109.20200228/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.gff.gz`

`gunzip GCF_000001405.39_GRCh38.p13_genomic.gff.gz`

2) convert to genePred format
`gff3ToGenePred GCF_000001405.39_GRCh38.p13_genomic.gff GCF_000001405.39_GRCh38.p13_genomic.genePred`

3) convert from genePred to gff3
`genePredToGtf file GCF_000001405.39_GRCh38.p13_genomic.genePred GCF_000001405.39_GRCh38.p13_genomic.withTranscripts.gtf`

4) test with TALON reformat_gtf.py
`python3 /home/ehutchins/tools/TALON/src/talon/reformat_gtf.py -g GCF_000001405.39_GRCh38.p13_genomic.withTranscripts.gtf`

Voila!

**Comment by e-hutchins** [comment]
5. replace description with "BestRefSeq" 
`sed -i 's/GCF_000001405.39_GRCh38.p13_genomic.genePred/BestRefSeq/' GCF_000001405.39_GRCh38.p13_genomic.withTranscripts.gtf`

6. add header back in
`cat header.txt GCF_000001405.39_GRCh38.p13_genomic.withTranscripts.gtf > GCF_000001405.39_GRCh38.p13_genomic.withTranscripts.gtf`

**Comment by e-hutchins** [comment]
OK, ignore most of the above. I wrote a bash script to add the transcript lines to the original gtf. It may or may not need to be sorted depending on how it's processed downstream.
